name: build-analyze-deploy

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis relevancy

    - name: Login to Docker Hub
      uses: docker/login-action@v3

    - name: Docker Build and push
      run: |
        docker build -t naresh3451213/wiseow-app:latest .
        docker tag wisecow-app naresh3451213/wiseow-app:latest
        docker push naresh3451213/wiseow-app:latest
